<div class="row">

    <div class="footer">

        <footer class="font-small col-12">

            <div class="container text-center text-md-left">

                <div class="row">

                    <div class="col-md-6 mx-auto">

                        <h5 class="text-uppercase font-weight-bold  mt-3 mb-4 ">Over ons</h5>
                        <p class="foot_text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente
                            sint, nulla, nihil
                            repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam
                            recusandae
                            harum esse fugiat. </p>

                    </div>

                    <hr class="clearfix w-100 d-md-none">

                    <div class="col-md-3 mx-auto">

                        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

                        <ul class="list-unstyled">
                            <li>
                                <a href="#!">Link 1</a>
                            </li>
                            <li>
                                <a href="#!">Link 2</a>
                            </li>
                            <li>
                                <a href="#!">Link 3</a>
                            </li>
                            <li>
                                <a href="#!">Link 4</a>
                            </li>
                        </ul>

                    </div>

                    <hr class="clearfix w-100 d-md-none">

                    <div class="col-md-3 mx-auto">

                        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Contact</h5>

                        <ul class="list-unstyled">
                            <li>
                                Adres: Zuiderpalen 22, 8321 AL Urk
                            </li>
                            <li>
                                Email: urkIsEenEiland@gmail.com
                            </li>
                            <li>
                                Tel: + 0557 643 322
                            </li>

                        </ul>


                    </div>

                </div>

            </div>

            <div class="footer-copyright text-center py-3">© 2019 Copyright: ChainGang</div>

        </footer>


    </div>
</div>
</div>

