<div class="Footer">
    <div class="Tabel">
        <table>
            <tr>
                <th>Klanten Service</th>
            </tr>
            <tr>
                <td>Bestellingen</td>
            </tr>
        </table>
    </div>

    <div class="Tabel">
        <table>
            <tr>
                <th>Zakelijk</th>
            </tr>
            <tr>
                <td>Zakelijke dingen</td>
            </tr>
        </table>
    </div>

    <div class="Tabel">
        <table>
            <tr>
                <th>Winkels</th>
            </tr>
            <tr>
                <td>Niet</td>
            </tr>
        </table>
    </div>

    <div class="Tabel">
        <table>
            <tr>
                <th>Over Fiets</th>
            </tr>
            <tr>
                <td>Over ons</td>
            </tr>
        </table>
    </div>


</div>

</div>