<div class="Footer">
    <table>
        <thead>
            <tr>
                <td>Klanten Service</td>
                <td>Zakelijk</td>
                <td>Winkels</td>
                <td>Info</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <ul>
                        <li>flikker</li>
                        <li>op</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</div>

</div>