<div class="Container">
    <div class="Header">
        <div class="Logo">
            <img src="img/Fiets.png" class="Foto" alt="fiets">
        </div>

        <div class="Zoek">
            <form class="Form">
                <input type="text" class="ZoekBalk">
                <input type="submit" class="Button" value="a">
            </form>
        </div>

        <div class="Menu">
            <list>
                <ul>
                    <li>
                        <p href="#" class="info">Fietsen &#8897;
                            <span class="spanInfo">Alle &#8594;
                                <a href="#" class="aInfo">Alle</a>
                                <a class="aInfo" href="#" style="margin-top: 11px">Mountain bike</a>
                                <a href="#" class="aInfo" style="margin-top: 61px">Race fiets</a>
                                <a class="aInfo" href="#" style="margin-top: 111px; height: 28px;">Stad fiets</a>

                            </span>
                            <span class="spanInfo" style="margin-top: 45px">Mannen &#8594;
                                <a href="#" class="aInfo">Alle </a>
                                <a class="aInfo" href="#" style="margin-top: 16px">Mountain bike</a>
                                <a href="#" class="aInfo" style="margin-top: 66px">Race fiets</a>
                                <a class="aInfo" href="#" style="margin-top: 115px">Stad fiets</a>
                            </span>
                            <span class="spanInfo" style="margin-top: 95px">Vrouwen &#8594;
                                <a href="#" class="aInfo">Alle</a>
                                <a class="aInfo" href="#" style="margin-top: 16px">Mountain bike</a>
                                <a href="#" class="aInfo" style="margin-top: 66px">Race fiets</a>
                                <a class="aInfo" href="#" style="margin-top: 115px">Stad fiets</a>

                            </span>
                            <span class="spanInfo" style="margin-top: 145px; height: 28px">Kinderen &#8594;
                                <a href="#" class="aInfo">Alle</a>
                                <a class="aInfo" href="#" style="margin-top: 16px">Mountain bike</a>
                                <a href="#" class="aInfo" style="margin-top: 66px">Race fiets</a>
                                <a class="aInfo" href="#" style="margin-top: 115px">Stad fiets</a>

                            </span>
                        </p>
                    </li>

                </ul>
            </list>


        </div>

    </div>
    <div class="Content">

