<div class="container border">
    <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-light col-12">
            <a class="navbar-brand" href="home"><img height="50" src="img/Fiets.png"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="catogorie">Catogorien</a>
                    </li>
                </ul>
                
                <div class="navbar-text" style="margin-right: 20px">
                    <?php
                        if(isset($data["user"]))
                        {
                            ?>
                            <a style="margin-right: 20px;" href="#"><?=$data["user"]->getFullName()?></a>
                            <a href="home?logout=true">Uitloggen</a>
                            <?php
                        }
                        else
                        {
                            ?>
                            <a style="margin-right: 20px;" href="login?return=<?=$data["page"] == "" ? "home" : $data["page"]?>">Inloggen</a>
                            <a href="register">Registreren</a>
                            <?php
                        }
                    ?>
                </div>

                <form class="form-inline">
                    <div class="input-group">
                        <input type="text" class="form-control border-dark" placeholder="Search">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </nav>
    </div>