<title><?=$data["title"] . " - ChainGang"?></title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<?php
if(isset($_GET["thanos"]))
{
    if($_GET["thanos"] == "true")
    {
        ?>
        <script src="js/html2canvas.min.js"></script>
        <script src="js/chance.min.js"></script>
        <script src="js/Thanos.js"></script>
        <?php
    }
}
?>
