<div class="Container">
    <div class="Header">
        <div class="Logo">
            <img src="img/Fiets.png" class="Foto" alt="fiets">
        </div>
        <div style="height:100%; width:700px; float:left;">
            <form>
                <table class="Zoek">
                    <tr>
                        <td><input type="text" class="ZoekBalk"></td>
                        <td><input type="submit" class="Button" value="&#x1F50E;" style="width:auto;"</td>
                        <td>profiel naam</td>
                        <td>uitloggen</td>
                        <td>winkel wagen</td>
                    </tr><!--zoek resultaten hier onder met jquerry-->
                </table>
            </form>

            <ul class="top-level-menu">
                <li>
                    <a>Catogorien</a>
                    <ul class="second-level-menu">
                        <li><a href="#">Mannen</a></li>
                        <li><a href="#">Vrouwen</a></li>
                        <li>
                            <a href="#">Kinderen</a>
                            <ul class="third-level-menu">
                                <li><a href="#">kinder ding 1</a></li>
                                <li><a href="#">kinder ding 2</a></li>
                                <li><a href="#">kinder ding 3</a></li>
                                <li><a href="#">kinder ding 4</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
        <div class="Content">

