<div class="ProductBody col-md-4  mx-auto">
    <img href="" width="200" height="200" type="image" src="<?=$product->getImage()?>" alt="<?=$product->getName()?>" class="ProductFoto">

    <h4><?=$product->getName()?></h4>
    <p class="ProductPrijs">€ <?=$product->getPrijs()?></p>
    <p><?=$product->getDiscription()?></p>
    <button name="veranderFoto" type="submit" class="ProductKnop" onclick="addToCart(<?=$product->getId()?>)">voeg aan winkelwagen toe</button>

</div>