<!DOCTYPE html>

<?php require ('../lib/functions.php'); ?>

    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="../../public/css/Product.css">

<div id="product">
    <!--<img src="../../public/img/Fiets.png" alt="fiets" id="foto">-->
    <input href="" type="image" src="../../public/img/Fiets.png" alt="fiets" id="foto">

    <p id="prijs">$ 0,00</p>
    <h4>product name</h4>

    <p>product bechrijving</p>

    <form method="post">
    <input name="veranderFoto" type="submit" id="knop" value="voeg aan winkelwagen toe">
    </form>

</div>