
    <div class="col-md-2 border">
        <div class="col-sm-2"><a class="linkjes" href="profiel">Profiel</a></div>
        <!--<div class="col-sm-2"><a class="linkjes" href="profiel/bestellingen">Bestellingen</a></div>-->
        <div class="col-sm-2"><a class="linkjes" href="profiel/facturen">Bestellingen</a></div>
        <div class="col-sm-2"><a class="linkjes" href="profiel/adres">Adres</a></div>
        <div class="col-sm-2"><a class="linkjes" href="profiel/wijzigen">Wijzigen</a></div>
    </div>












