
    <div class="col-md-2 border">
        <div class="col-sm-2"><a class="linkjes" href="profiel">Profiel</a></div>
        <div class="col-sm-2"><a class="linkjes" href="profiel/bestellingen">Bestellingen</a></div>
        <div class="col-sm-2"><a class="linkjes" href="profiel/facturen">Facturen</a></div>
        <div class="col-sm-2"><a class="linkjes">Yeet</a></div>
        <div class="col-sm-2"><a class="linkjes">Yeet</a></div>
    </div>












