<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <link rel="stylesheet" href="css/Profiel.css">
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?> <!--Import Header-->

        <div class="row">
            <?php include config["TEMPLATE_FOLDER"] . "ProfielSideBar.phtml" ?>

            <div class="col-md-4">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <table class="table">
                            <tr>
                                <th>Adres</th>
                                <th>Stad</th>
                                <th>Postcode</th>
                            </tr>
                        <?php
                        foreach ($data["adresses"] as $adress)
                        {
                            ?>
                            <tr>
                                <td><?= $adress->getStreet() . " " . $adress->getHouseNumber()?></td>
                                <td><?= $adress->getCity() ?></td>
                                <td><?= $adress->getPostCode() ?></td>
                            </tr>

                            <?php
                        }
                        ?>
                        </table>
                    </div>
                </div>

                <!--Einde Content-->
                <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?> <!--Import Footer-->
    </body>
</html>