<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <link rel="stylesheet" href="css/Profiel.css">
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?> <!--Import Header-->

        <!--↓↓↓-->

        <div class="row">
            <?php include config["TEMPLATE_FOLDER"] . "ProfielSideBar.phtml" ?>

            <table class="table col-8 bestellingen">
                <thead>
                    <tr>
                        <th scope="col">Bestelling nummer</th>
                        <th scope="col">Producten</th>
                        <th scope="col">Prijs</th>
                        <th scope="col">Betaald</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1500</th>
                        <td>Fiets gazelle 1 <br> Fiets gazelle 2 <br> Fiets gazelle 5</td>
                        <td>1999.99</td>
                        <td>Nee</td>
                    </tr>
                    <tr>
                        <th scope="row">1488</th>
                        <td>Fiets gazelle 7</td>
                        <td>1099.99</td>
                        <td>ja</td>
                    </tr>
                    <tr>
                        <th scope="row">88</th>
                        <td>Fiets gazelle 3</td>
                        <td>499.99</td>
                        <td>ja</td>
                    </tr>
                </tbody>
            </table>

        </div>
        <!--↑↑↑-->

        <!--Einde Content-->
        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?> <!--Import Footer-->
    </body>
</html>