<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <link rel="stylesheet" href="css/Profiel.css">
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?>     <!--Import Header-->
        <!--Content-->
        <div class="row">
            <?php include config["TEMPLATE_FOLDER"] . "ProfielSideBar.phtml" ?>

            <div class="col-md-9">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Bestellingen</strong></h3>
                    </div>
                    <?php
                    foreach ($data["facturen"] as $factuur)
                    {
                        ?>
                    <div class="table-responsive">
                        <table class="table table-condensed" style="margin-bottom: 50px">
                            <thead>
                                <tr>
                                    <td><strong>Product</strong></td>
                                    <td class="text-center"><strong>Prijs</strong></td>
                                    <td class="text-center"><strong>Aantal</strong></td>
                                    <td class="text-right"><strong>Totaal</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                <?php

                                foreach ($factuur->getProducts() as $shipProduct)
                                {
                                    ?>
                                    <tr>
                                        <td><?=$shipProduct->getProduct()->getName()?></td>
                                        <td class="text-center">€ <?=$shipProduct->getProduct()->getPrijs()?></td>
                                        <td class="text-center"><?=$shipProduct->getCount()?></td>
                                        <td class="text-right">€ <?=$shipProduct->getTotal()?></td>
                                    </tr>
                                    <?php
                                }
                                ?>
                                    <tr>
                                        <td class="no-line"></td>
                                        <td class="no-line"></td>
                                        <td class="no-line text-center"><strong>Sub totaal</strong></td>
                                        <td class="no-line text-right">€ <?=$factuur->getTotal()?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <?php
                    }
                    ?>
                    </div>

            </div>
        </div>

            <div class="row">
                <div class="col-md-12">
                    <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?>     <!--Import Footer-->

                </div>
            </div>

    </body>
</html>