<!DOCTYPE html>
<html lang="nl">
<head>
    <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
    <link rel="stylesheet" href="css/Product.css">
</head>
<body>
<?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?>     <!--Import Header-->
<!--Content-->


    <div class="row">
        <?php include config["TEMPLATE_FOLDER"] . "Product.phtml";?>

        <?php include config["TEMPLATE_FOLDER"] . "Product.phtml";?>

        <?php include config["TEMPLATE_FOLDER"] . "Product.phtml";?>

        <?php include config["TEMPLATE_FOLDER"] . "Product.phtml";?>

        <?php include config["TEMPLATE_FOLDER"] . "Product.phtml";?>

        <?php include config["TEMPLATE_FOLDER"] . "Product.phtml";?>

        <?php include config["TEMPLATE_FOLDER"] . "Product.phtml";?>

        <?php include config["TEMPLATE_FOLDER"] . "Product.phtml";?>
    </div>


<!--Einde Content-->
<?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?>     <!--Import Footer-->
</body>
</html>