<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <link href="css/Detail.css" rel="stylesheet">
    </head>
    <body>

        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?> <!--Import Header-->
        <!--Content-->

            <div class="row" class="margin-top: 50px">
                <div class="col-6"><img class="prodFoto" alt="<?= $data["item"]->getName()?>" src="<?= $data["item"]->getImage()?>"></div>

                <div class="col-6">
                    <h1><?= $data["item"]->getName()?> </h1>
                    <p><?= $data["item"]->getDiscription()?></p>
                </div>

            </div>
            <div class="row" style="margin-left: 50px">
            <h4>€ <?= $data["item"]->getPrijs()?></h4>

                <div class="col-md-4"><button class="btn btn-primary" style="background: #199ed8" onclick="addToCart(<?=$data['item']->getId()?>)">Voeg toe</button></div>
            </div>

            <div class="row">
            </div>
        <br>
        <br>
        <br>
        <!--Einde Content-->
        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?> <!--Import Footer-->

    </body>
</html>