<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?>     <!--Import Header-->
        <!--Content-->
        <div class="container">
            <div class="row">
                <div class="col col-md-4">
                    <h3>Fiets afbeelding hier met aanbieding</h3>
                </div>
                <div class="col col-md-4">
                    <h3>Fiets afbeelding hier met aanbieding</h3>
                </div>
                <div class="col col-md-4">
                    <h3>Fiets afbeelding hier met aanbieding</h3>
                </div>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col col-md-3">
                    <h4>Fiets afbeelding hier met knop(JongenFietsen)</h4>
                </div>
                <div class="col col-md-3">
                    <h4>Fiets afbeelding hier met knop(MeisjesFietsen)</h4>
                </div>
                <div class="col col-md-3">
                    <h4>Fiets afbeelding hier met knop(HerenFietsen)</h4>
                </div>
                <div class="col col-md-3">
                    <h4>Fiets afbeelding hier met knop(DamesFietsen)</h4>
                </div>
            </div>
        </div>
        <br><br>

        <div class="container">
            <div class="row">
                <div class="col">
                    <h1>Nieuwe Fietsen </h1>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col col-md-3">
                    <h4>Nieuwe Fiets </h4>
                </div>
                <div class="col col-md-3">
                    <h4>Nieuwe Fiets </h4>
                </div>
                <div class="col col-md-3">
                    <h4>Nieuwe Fiets </h4>
                </div>
                <div class="col col-md-3">
                    <h4>Nieuwe Fiets </h4>
                </div>
                <div class="col col-md-3">
                    <h4>Nieuwe Fiets </h4>
                </div>
                <div class="col col-md-3">
                    <h4>Nieuwe Fiets </h4>
                </div>
                <div class="col col-md-3">
                    <h4>Nieuwe Fiets </h4>
                </div>
                <div class="col col-md-3">
                    <h4>Nieuwe Fiets </h4>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col">
                    <h1>Vind onze winkels </h1>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col">
                    <h1>hier google maps gedeelte met locaties</h1>
                </div>
            </div>
        </div>

        <!--Einde Content-->
        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?>     <!--Import Footer-->
    </body>
</html>