<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <script src="js/Review.js"></script>
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?>     <!--Import Header-->
        <!--Content-->

        <h1><?=isset($data["user"]) ? $data["user"]->getFullName() : "Ur mom"?> is dik</h1>
        <?php include config["TEMPLATE_FOLDER"] . "Review.phtml" ?>

        <!--Einde Content-->
        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?>     <!--Import Footer-->
    </body>
</html>