<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?>     <!--Import Header-->
        <!--Content-->
        <form>
            <input type="text">
            <input type="text">
            <input type="submit">
        </form>
        <!--Einde Content-->
        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?>     <!--Import Footer-->
    </body>
</html>