<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <link rel="stylesheet" href="css/login.css">
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?>     <!--Import Header-->
        <!--Content-->
        <form method="POST" class="LoginForm" action="login<?=isset($_GET["return"]) ? ("?return=" . $_GET["return"]) : ""?>">
            <table>
                <tr class="CenterTr">
                    <td colspan="2" style="text-align: center"><h1>Inloggen</h1></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td><input class="LoginInput" type="text" name="email"></td>
                </tr>
                <tr>
                    <td>Wachtwoord</td>
                    <td><input class="LoginInput" type="password" name="password"></td>
                </tr>
                <tr class="CenterTr">
                    <td colspan="2"><input class="LoginButton" type="submit" value="Login"></td>
                </tr>
                <tr class="CenterTr">
                    <td colspan="2"><?php if(isset($data["errorMsg"])){echo "<p style='text-align:center; color: red;'>". $data["errorMsg"] ."</p>";}?></td>
                </tr>
            </table>
        </form>

        <!--Einde Content-->
        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?>     <!--Import Footer-->
    </body>
</html>