<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <link rel="stylesheet" href="css/Profiel.css">
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?> <!--Import Header-->

        <!--↓↓↓-->

        <div class="row">
            <?php include config["TEMPLATE_FOLDER"] . "ProfielSideBar.phtml" ?>

            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-4">
                                <label>Voornaam</label>
                            </div>
                            <div class="col-md-4">
                                <p><?= $data["firstname"] ?></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Achternaam</label>
                            </div>
                            <div class="col-md-4">
                                <p><?= $data["lastname"] ?></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Email</label>
                            </div>
                            <div class="col-md-4">
                                <p><?= $data["email"] ?></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Wachtwoord Wijzigen</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                <!--↑↑↑-->
                <!--Einde Content-->

                <div class="row">
                    <div class="col-md-12">
                        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?> <!--Import Footer-->

                    </div>
                </div>
    </body>
</html>