<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <link rel="stylesheet" href="css/Profiel.css">
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?> <!--Import Header-->

        <!--↓↓↓-->

        <div class="row">
            <?php include config["TEMPLATE_FOLDER"] . "ProfielSideBar.phtml" ?>

            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-4">
                                <label>Voornaam</label>
                            </div>
                            <div class="col-md-4">
                                <p>*Voornaam*</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Achternaam</label>
                            </div>
                            <div class="col-md-4">
                                <p>*Achternaam*</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Email</label>
                            </div>
                            <div class="col-md-4">
                                <p>*Email*</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Telefoon Nummer</label>
                            </div>
                            <div class="col-md-4">
                                <p>*Telefoon Nummer*</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Adres</label>
                            </div>
                            <div class="col-md-4">
                                <p>*Adres*</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Post code</label>
                            </div>
                            <div class="col-md-4">
                                <p>*Post code*</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Woonplaats</label>
                            </div>
                            <div class="col-md-4">
                                <p>*Woonplaats*</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <a href="#">Wachtwoord vergeten</a>
                            </div>
                        </div>
                    </div>
        </div>
        <!--↑↑↑-->

        <!--Einde Content-->
        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?> <!--Import Footer-->
    </body>
</html>